{% set sdk_version = "3.1.426" %}
{% set runtime_version = "3.1.32" %}
{% set sha256 = "7e396017a3e32b0209406c73ead9f4c03d3f521768fcd548d02a0ff5c3d45593" %}  # [aarch64]
{% set sha256 = "cce481c054c331ad57e26e5d326993b2209a61b4df66118e7bae878d09f51dc1" %}  # [linux]
{% set sha256 = "6b0792f2be40a279ebbee284b6bc4e955c8242401f2b254a9a975ff477c7e535" %}  # [osx]
{% set sha256 = "a0a7f5cf9d7030ca7e5cc805ef46082ffbf9d42ed5b39010c0fb84acda45f45e" %}  # [win]
{% set platform = "linux-arm64" %}    # [aarch64]
{% set platform = "linux-x64" %}  # [linux]
{% set platform = "osx-x64" %}    # [osx]
{% set platform = "win-x64" %}    # [win]
{% set ext = "tar.gz" %}      # [not win]
{% set ext = "zip" %}         # [win]

package:
  name: dotnet
  version: {{ sdk_version }}

source:
  url: https://dotnetcli.azureedge.net/dotnet/Sdk/{{ sdk_version }}/dotnet-sdk-{{ sdk_version }}-{{ platform }}.{{ ext }}
  sha256: {{ sha256 }}
  folder: dotnet

build:
  number: 0

outputs:
  - name: dotnet
    version: {{ sdk_version }}
    requirements:
      run:
        - {{ pin_subpackage('dotnet-runtime', exact=True) }}
        - {{ pin_subpackage('dotnet-aspnetcore', exact=True) }}
        - {{ pin_subpackage('dotnet-desktop', exact=True) }}  # [win]
        - {{ pin_subpackage('dotnet-sdk', exact=True) }}
    test:
      commands:
       - dotnet --version

  - name: dotnet-runtime
    version: {{ runtime_version }}
    script: build-runtime.bat       # [win]
    script: build-runtime.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
    test:
      commands:
        - dotnet --list-runtimes
        - test "${DOTNET_ROOT}" = "${CONDA_PREFIX}/lib/dotnet"         # [unix]
        - test "${DOTNET_TOOLS}" = "${CONDA_PREFIX}/lib/dotnet/tools"  # [unix]
        - if not defined DOTNET_ROOT exit 1   # [win]
        - if not defined DOTNET_TOOLS exit 1  # [win]
    about:
      home: https://github.com/dotnet/runtime
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-sdk
    version: {{ sdk_version }}
    script: build-sdk.bat       # [win]
    script: build-sdk.sh        # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust             # [linux64]
        - libcurl               # [unix]
        - icu                   # [unix]
        - krb5                  # [unix]
        - __glibc >=2.17        # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - dotnet --version                   # [not aarch64]
        - test -f $PREFIX/lib/dotnet/dotnet  # [aarch64]
      home: https://github.com/dotnet/sdk
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-aspnetcore
    version: {{ runtime_version }}
    script: build-aspnetcore.bat    # [win]
    script: build-aspnetcore.sh     # [not win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - posix                  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - zlib                   # [unix]
        - libcurl                # [unix]
        - lttng-ust              # [linux64]
      run:
        - lttng-ust                 # [linux64]
        - libcurl                   # [unix]
        - icu                       # [unix]
        - krb5                      # [unix]
        - __glibc >=2.17            # [linux64]
        - dotnet-runtime ={{ runtime_version }}
    test:
      commands:
        - test -d $PREFIX/lib/dotnet/shared/Microsoft.AspNetCore.App              # [not win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.AspNetCore.App exit 1  # [win]
    about:
      home: https://github.com/dotnet/aspnetcore
      license: MIT
      license_file: dotnet/LICENSE.txt
      summary: |
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

  - name: dotnet-desktop                                                              # [win]
    version: {{ runtime_version }}                                                    # [win]
    script: build-desktop.bat                                                         # [win]
    requirements:                                                                     # [win]
      build:                                                                          # [win]
        - posix                                                                       # [win]
      run:                                                                            # [win]
        - dotnet-runtime ={{ runtime_version }}                                       # [win]
    test:                                                                             # [win]
      commands:                                                                       # [win]
        - if not exist %PREFIX%\\dotnet\\shared\\Microsoft.WindowsDesktop.App exit 1  # [win]
    about:                                                                            # [win]
      home: https://github.com/dotnet/desktop                                         # [win]
      license: MIT                                                                    # [win]
      license_file: dotnet/LICENSE.txt                                                # [win]
      summary: |                                                                      # [win]
        .NET Core is a free and open-source managed computer software
        framework for the Windows, Linux, and macOS operating systems.

about:
  home: https://github.com/dotnet/core
  license: MIT
  license_file: dotnet/LICENSE.txt
  summary: |
    .NET Core is a free and open-source managed computer software
    framework for the Windows, Linux, and macOS operating systems.

extra:
  recipe-maintainers:
    - dhirschfeld
    - ZimmerA
    - acesnik
