export _CONDA_BACKUP_DOTNET_ROOT=$DOTNET_ROOT
export _CONDA_BACKUP_DOTNET_TOOLS=$DOTNET_TOOLS

export DOTNET_ROOT=$CONDA_PREFIX/lib/dotnet
export DOTNET_TOOLS=$DOTNET_ROOT/tools

export DOTNET_CLI_TELEMETRY_OPTOUT=true
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
export DOTNET_ADD_GLOBAL_TOOLS_TO_PATH=false

export PATH="${DOTNET_ROOT}:${DOTNET_TOOLS}${PATH:+:${PATH}}"
